[project]
name = "forked-geval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.101.0",
    "prettytable>=3.16.0",
    "python-dotenv>=1.1.1",
    "scipy>=1.16.1",
]
